name: Build and Push Docker Image
permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # Uruchomienie dla wielu architektur (arm64 i amd64)
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to DockerHub (dla cache registry)
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and export cache
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/pogoda-app:latest
          ghcr.io/${{ github.repository_owner }}/pogoda-app:${{ github.sha }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/pogoda-app-cache:latest
        cache-to: type=registry,mode=max,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/pogoda-app-cache:latest

    - name: Scan image for CVEs (Trivy)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ghcr.io/${{ github.repository_owner }}/pogoda-app:latest
        severity: CRITICAL,HIGH
        ignore-unfixed: true
        format: table

    - name: Conditional push if scan passed
      if: success()
      run: echo "Scan passed — image published ✅"
